alpha/urls.py
from django.urls import path,reverse_lazy
from . import views


app_name='alpha'
urlpatterns = [
path('', views.index, name='index'),
path('createuser/',views.createuser.as_view(),name='createuser'),
path('indata/',views.indata),
path('dashboard/',views.dashboard.as_view(),name='dashboard'),
path('createwarehouse/',views.createwarehouse.as_view(success_url=reverse_lazy('alpha:dashboard')),name='createwarehouse'),
path('editwarehouse/<int:pk>/',views.editwarehouse.as_view(success_url=reverse_lazy('alpha:dashboard')),name='editwarehouse'),
path('deletewarehouse/<int:pk>/',views.deletewarehouse.as_view(success_url=reverse_lazy('alpha:dashboard')),name='deletewarehouse')
]

coldstorage/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('alpha/',include('alpha.urls')),
    path('',include('alpha.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

alpha/models.py
from django.db import models
from django.contrib.auth.models import (BaseUserManager,AbstractBaseUser)
from django.core.validators import RegexValidator
from django.core.validators import MinLengthValidator
import datetime



class PeopleUserManager(BaseUserManager):
    def create_user(self, email, date_of_birth, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(
        email=self.normalize_email(email),
        date_of_birth=date_of_birth,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, date_of_birth, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
        email,
        password=password,
        date_of_birth=date_of_birth,
                )
        user.is_admin = True
        user.save(using=self._db)
        return user

class People(AbstractBaseUser):
    email = models.EmailField(verbose_name='email address',max_length=255,unique=True,)
    date_of_birth = models.DateField()
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    objects = PeopleUserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['date_of_birth']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        return True

    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

class warehouse(models.Model):
    name=models.CharField(max_length=30)
    pincode=models.CharField(max_length=6,validators=[RegexValidator('^[0-9][0-9][0-9][0-9][0-9][0-9]$',"enter only numbers")])
    countrycode=models.CharField(max_length=4)
    people = models.ManyToManyField(People)

class inwarehouse(models.Model):
    warehouse=models.ForeignKey(warehouse,on_delete=models.CASCADE)
    temperature=models.FloatField()
    humidity=models.FloatField()
    dateandtime=models.DateTimeField(default=datetime.datetime.now)

alpha/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,JsonResponse
from alpha.admin import UserCreationForm as Form
from django.urls import reverse
from django.views import View
from alpha.models import warehouse,People,inwarehouse
from urllib.request import urlopen
import json
from datetime import datetime,timedelta
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.csrf import csrf_exempt

def index(request):
    return render(request,'alpha/index.html')

@csrf_exempt
def indata(request):
    if request.method=="POST":
        x=json.loads(request.body.decode())
        ware_ins=warehouse.objects.get(pk=x["warehouse"])
        n=inwarehouse(warehouse=ware_ins,temperature=x["temperature"],humidity=x["humidity"],dateandtime=datetime.now())
        n.save()
        return HttpResponse(datetime.now())
    else:
        return HttpResponse("YOU HAVE USED GET METHOD")


class dashboard(LoginRequiredMixin,View):

    def get(self,request):
        today=datetime.now()
        ttime=str(today.time()).split('.')[0]
        tomorrow=today+timedelta(1)
        today=today.date()
        tomorrow=tomorrow.date()
        x = People.objects.get(id=request.user.id).warehouse_set.all()
        l=[]
        alert=[]
        for j in x:
            d={}
            d["name"]=j.name
            d["id"]=j.id
            d["pincode"]=j.pincode
            d["countrycode"]=j.countrycode
            d["id"]=j.id
            try:
                lat_updt=inwarehouse.objects.filter(warehouse_id=j.id).order_by('id')[::-1][0]
                d["iw"]={"temperature":lat_updt.temperature,"humidity":lat_updt.humidity,"updated":lat_updt.dateandtime}
                print(d["iw"])
            except:
                d["iw"]={"temperature":None,"humidity":None,"updated":None}


            response=urlopen("http://api.openweathermap.org/data/2.5/weather?zip={},IN&appid=710833e8507eaccc99e34ceaf6d24884".format(j.pincode))
            data=json.loads(response.read())
            d["cw"]={"weather":data["weather"][0]["description"],"temp":"{:.2f}".format(data["main"]["temp"]-273.15),"humidity":"{:.2f}".format(data["main"]["humidity"]),"wind_speed":"{:.2f}".format(data["wind"]["speed"])}

            if float(d["cw"]["temp"])>40 or float(d["cw"]["temp"])<0:
                alert.append([j.name,j.pincode,today,ttime,"temperature",d["cw"]["temp"]])
            elif float(d["cw"]["humidity"])>0:
                alert.append([j.name,j.pincode,str(today),ttime,"humidity",d["cw"]["humidity"]])

            response=urlopen("http://api.openweathermap.org/data/2.5/forecast?zip={},IN&appid=710833e8507eaccc99e34ceaf6d24884".format(j.pincode))
            data=json.loads(response.read())

            tw_weather=[]
            tw_temp=0
            tw_humidity=0
            tw_wind_speed=0

            for i in data['list']:
                iter=datetime.fromtimestamp(i['dt'])
                if iter.date()==today:
                    continue
                elif iter.date()==tomorrow:

                    tw_weather.append(i['weather'][0]["description"])
                    tw_temp+=i["main"]["temp"]-273.15
                    tw_humidity+=i["main"]["humidity"]
                    tw_wind_speed+=i["wind"]["speed"]
                    if i["main"]["temp"]-273.15>40 or i["main"]["temp"]<0:
                        alert.append([j.name,j.pincode,str(iter.date()),str(iter.time()),"temperature",i["main"]["temp"]])
                    elif i["main"]["humidity"]>0:
                        alert.append([j.name,j.pincode,str(iter.date()),str(iter.time()),"humidity",i["main"]["humidity"]])
                    continue
                break

            tw_weather_str=" & ".join(set(tw_weather))
            d["tw"]={"weather":tw_weather_str,"temp":"{:.2f}".format(tw_temp/8),"humidity":"{:.2f}".format(tw_humidity/8),"wind_speed":"{:.2f}".format(tw_wind_speed/8)}

            l.append(d)


        ctx={'warehouse_list':l,"alert":alert}

        return render(request,'alpha/dashboard.html',ctx)


class createwarehouse(LoginRequiredMixin,CreateView):
    model = warehouse
    fields = ['name','pincode']
    template_name = 'alpha/warehouse.html'


    def form_valid(self, form):
        object = form.save(commit=False)
        object.countrycode='IN'
        x=super(createwarehouse,self).form_valid(form)
        print(x)
        if x:
            object.people.add(self.request.user.id)
        return x

class editwarehouse(LoginRequiredMixin,UpdateView):
    model = warehouse
    fields = ['name','pincode']
    template_name = 'alpha/warehouse.html'

class deletewarehouse(LoginRequiredMixin,DeleteView):
    model = warehouse
    template_name = 'alpha/warehouse_delete.html'

class createuser(View):
    def get(self, request):
        form=Form()
        ctx={'form':form}
        return render(request,'alpha/createuser.html',ctx)

    def post(self, request) :
        form = Form(request.POST)
        if not form.is_valid() :
            ctx = {'form' : form}
            return render(request, 'alpha/createuser.html', ctx)

        alpha = form.save()
        x = reverse('alpha:index')
        return redirect(x)

alpha/templates/alpha/createuser.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CREATE USER</title>
    {% load static %}
    <link href="{% static 'alpha/css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'alpha/js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
  </head>
  <body>
    <div class="container-lg p-5 my-5 bg-dark text-white" style="align-content:center;">
      <div class="container">
        <form action="" method="post" id="form_tag">
          {% csrf_token %}
            {% for hidden_field in form.hidden_fields %}
              {{ hidden_field.errors }}
              {{ hidden_field }}
            {% endfor %}
            {% for field in form.visible_fields %}
              {{ field.label_tag }}
                  {{ field.errors }}
                  {{ field }}
                  {{ field.help_text }}
              {% endfor %}
        <br>
        <input class="btn btn-primary" type="submit" value="Submit">
        <input class="btn btn-primary" type="submit" onclick="window.location='{% url 'alpha:index' %}' ; return false;" value="Cancel">
        </form>
        <script type="text/javascript">
          var l1=document.getElementsByTagName('label');
          for (i=0;i<l1.length;i++){
            document.getElementsByTagName('label')[i].className+="form-label";
          }
          var l2=document.getElementsByTagName('input');
          for (i=0;i<l2.length-2;i++){
            document.getElementsByTagName('input')[i].className+="form-control";
          }
        </script>
      </div>
    </div>
  </body>
</html>

alpha/templates/alpha/dashboard.html
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" ></script>
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Dashboard</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" ></script>
    {% load static %}
    <link l="canonical" href="https://getbootstrap.com/docs/5.2/examples/cover/">
    <link href="{% static 'alpha/css/bootstrap.min.css' %}" rel="stylesheet">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>
    <script src="{% static 'alpha/js/bootstrap.bundle.min.js' %}"></script>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark" aria-label="Dark offcanvas navbar">
      <div class="container-fluid">
        <a class="navbar-brand">CSMSWML</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbarDark" aria-controls="offcanvasNavbarDark">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end text-white bg-dark" tabindex="-1" id="offcanvasNavbarDark" aria-labelledby="offcanvasNavbarDarkLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasNavbarDarkLabel"> {{ request.user.email }} </h5>
            <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'alpha:index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" style="color:white" href="{% url 'logout' %}?next={% url 'alpha:index' %}">log out</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>
    <br>
    <div class="container-fluid">
      <div class="container-fluidrow justify-content-start">
        <div class="col container-fluid">
          <a class="btn bg-info" href="{% url 'alpha:createwarehouse' %}?next={% url 'alpha:dashboard' %}">new warehouse</a>
        </div>
      </div>
    </div>
    <br>
    <div class="container-fluid" style="overflow:auto;">
    <table class="table bg-danger">
      <thead>
        <tr>
          <td>Warehouse</td>
          <td>Pincode</td>
          <td>Date</td>
          <td>Time</td>
          <td>Parms</td>
          <td>Value</td>
        </tr>
      </thead>
      <tbody>
        {% for a in alert %}
        <tr>
          {% for i in a %}
          <td>{{ i }}</td>
          {% endfor %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>


    <br>
    <div id="accordion">
      {% for warehouse in warehouse_list %}
      <div class="card" style="overflow:auto;">
        <div class="card-header">
          <div class="container-fluid">
            <span class="h6 btn" style="float:left">{{ warehouse.name }}</span>
            <span class="h6 btn bg-primary" style="float:right" data-bs-toggle="collapse" href="#collapse{{ warehouse.id }}">open</span>
          </div>
        </div>
        <div id="collapse{{ warehouse.id }}" class="collapse " data-bs-parent="#accordion">
          <div class="card-body container-fluid">
              <div class="container-fluid" style="align-items:center;">
                  <a class="btn bg-warning" href="{% url 'alpha:editwarehouse' warehouse.id %}">update</a>
                  <a class="btn bg-danger"  href="{% url 'alpha:deletewarehouse' warehouse.id %}">delete</a>
              </div>
              <br>
              <div class="container-fluid">
                <ul class="list-group">
                   <li class="list-group-item">ID : {{ warehouse.id }}</li>
                   <li class="list-group-item">Country code : {{ warehouse.countrycode }}</li>
                   <li class="list-group-item">Pincode : {{ warehouse.pincode}}</li>
                 </ul>
              </div>
              <br>
              <div class="row justify-content-around">
                <div class="col-lg-7 shadow-lg bg-dark table-responsive-lg mt-1" >
                  <table class="table table-hover table-striped table-dark">
                    <thead>
                      <tr>
                        <td>WEATHER PARMS</td>
                        <td>CURRENT</td>
                        <td>TOMMOROW</td>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>WEATHER</td>
                        <td>{{ warehouse.cw.weather }}</td>
                        <td>{{ warehouse.tw.weather }}</td>
                      </tr>
                      <tr>
                        <td>TEMPERATURE</td>
                        <td>{{ warehouse.cw.temp }}</td>
                        <td>{{ warehouse.tw.temp }}</td>
                      </tr>
                      <tr>
                        <td>HUMIDITY</td>
                        <td>{{ warehouse.cw.humidity }}</td>
                        <td>{{ warehouse.tw.humidity }}</td>
                      </tr>
                      <tr>
                        <td>WIND SPEED</td>
                        <td>{{ warehouse.cw.wind_speed }}</td>
                        <td>{{ warehouse.tw.wind_speed }}</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                <div class="col-lg-4 shadow-lg bg-dark table-responsive-lg mt-1">
                  <table class="table table-hover table-striped table-dark">
                    <thead>
                      <tr>
                        <td>IN WAREHOUSE</td>
                        <td>VALUES</td>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>TEMPERATURE</td>
                        <td>{{ warehouse.iw.temperature }}</td>
                      </tr>
                      <tr>
                        <td>HUMIDITY</td>
                        <td>{{ warehouse.iw.humidity }}</td>
                      </tr>
                      <tr>
                        <td>UPDATED</td>
                        <td>{{ warehouse.iw.updated }}</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </body>
</html>

alpha/templates/alpha/index.html
<!doctype html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.98.0">
    <title>COLD STORAGE</title>

    {% load static %}
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/cover/">
    <link href="{% static 'alpha/css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'alpha/css/cover.css' %}" rel="stylesheet">
  </head>
  <body class="d-flex h-100 text-center text-white bg-dark">

<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="mb-auto">
    <div>
      <h3 class="float-md-start mb-0">COLD STORAGE</h3>
      <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link fw-bold py-1 px-0 " style="color:white" href="{% url 'login' %}?next={% url 'alpha:index' %}">Login</a>
        <a class="nav-link fw-bold py-1 px-0 " style="color:white" href="{% url 'logout' %}?next={% url 'alpha:index' %}">Logout</a>
        <a class="nav-link fw-bold py-1 px-0 " style="color:white" href="{% url 'alpha:createuser' %}">Signup</a>
      </nav>
    </div>
  </header>

  <main class="px-3">
    <h1>Cold Storage Monitoring System With Machine Learning</h1>
    <p class="lead">To create an AI powered method to optimize storage of products and increase product quality</p>
    <p class="lead">

      <a class="btn btn-lg btn-secondary fw-bold border-white bg-white" href="{% url 'alpha:dashboard' %}">Dashboard</a>
    </p>
  </main>

  <footer class="mt-auto text-white-50">
    <p> Project @ <a href="http://skcet.ac.in/">skcet</a></p>
  </footer>
</div>



  </body>
</html>

alpha/templates/alpha/warehouse.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>WAREHOUSE</title>
    {% load static %}
    <link href="{% static 'alpha/css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'alpha/js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
  </head>
  <body>
    <div class="container-lg p-5 my-5 bg-dark text-white" style="align-content:center;">
      <div class="container">
        <form action="" method="post" id="form_tag">
          {% csrf_token %}
            {% for hidden_field in form.hidden_fields %}
              {{ hidden_field.errors }}
              {{ hidden_field }}
            {% endfor %}
            {% for field in form.visible_fields %}
              {{ field.label_tag }}
                  {{ field.errors }}
                  {{ field }}
                  {{ field.help_text }}
              {% endfor %}
        <br>
        <input class="btn btn-primary" type="submit" value="Submit">
        <input class="btn btn-primary" type="submit" onclick="window.location='{% url 'alpha:dashboard' %}' ; return false;" value="Cancel">
        </form>
        <script type="text/javascript">
          var l1=document.getElementsByTagName('label');
          for (i=0;i<l1.length;i++){
            document.getElementsByTagName('label')[i].className+="form-label";
          }
          var l2=document.getElementsByTagName('input');
          for (i=0;i<l2.length-2;i++){
            document.getElementsByTagName('input')[i].className+="form-control";
          }
        </script>
      </div>
    </div>
  </body>
</html>

alpha/templates/alpha/warehouse_delete.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>DELETE</title>
      {% load static %}
      <link href="{% static 'alpha/css/bootstrap.min.css' %}" rel="stylesheet">
      <script src="{% static 'alpha/js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
  </head>
  <body>
    <div class="container-lg p-5 my-5 bg-dark text-white" style="align-content:center;">
      <div class="container">
        <h1>Delete</h1>
        <p>Are you sure you want to delete the {{ warehouse.name }} ?</p>
        <form action="" method="POST">
          {% csrf_token %}
          <input type="submit" value="Yes, delete.">
        </form>
      </div>
    </div>
  </body>
</html>